# Generated by Django 4.2.1 on 2023-06-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_description_ordervehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('personal_page', models.URLField()),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.AlterField(
            model_name='buyer',
            name='area',
            field=models.CharField(choices=[('W', 'Windsor'), ('LS', 'LaSalle'), ('A', 'Amherstburg'), ('L', 'Lakeshore'), ('LE', 'Leamington'), ('C', 'Chatham'), ('T', 'Toronto'), ('WA', 'Waterloo')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
