# Generated by Django 4.2.1 on 2023-07-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_labmember_alter_buyer_area_alter_vehicle_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='features',
            field=models.CharField(blank=True, choices=[('CC', 'Cruise Control'), ('AI', 'Audio Interface'), ('AB', 'Airbags'), ('AC', 'Air Conditioning'), ('SH', 'Seat Heating'), ('PA', 'Park Assist'), ('PS', 'Power Steering'), ('RC', 'Reversing Camera'), ('AS', 'Auto Start/Stop')], max_length=2),
        ),
    ]
